import React from "react";
import PageBanner from "../../components/shared/PageBanner";
import Table from "../../components/shared/Table";

const HospitalOPD_IPD_Data = () => {
  return (
    <>
      <div className="mb-10">
        <PageBanner title="Hospital OPD & IPD Data" />
      </div>
      <Table
        title={"OPD Data - Year 2024"}
        columns={[
          { label: "S.No", key: "no" },
          { label: "Name of the Departments", key: "department" },
          { label: "Jan", key: "jan" },
          { label: "Feb", key: "feb" },
          { label: "Mar", key: "mar" },
          { label: "Apr", key: "apr" },
          { label: "May", key: "may" },
          { label: "Jun", key: "jun" },
          { label: "Jul", key: "jul" },
          { label: "Aug", key: "aug" },
          { label: "Sep", key: "sep" },
          { label: "Oct", key: "oct" },
          { label: "Nov", key: "nov" },
          { label: "Dec", key: "dec" },
          { label: "Dept. Total", key: "total" },
        ]}
        data={[
          {
            no: "1",
            department: "Kayachikitsa",
            jan: 1260,
            feb: 1271,
            mar: 1131,
            apr: 1199,
            may: 1206,
            jun: 993,
            jul: 1054,
            aug: 1041,
            sep: 1009,
            oct: 951,
            nov: 1000,
            dec: 1005,
            total: 13120,
          },
          {
            no: "2",
            department: "Panchakarma",
            jan: 707,
            feb: 737,
            mar: 687,
            apr: 712,
            may: 753,
            jun: 748,
            jul: 822,
            aug: 836,
            sep: 804,
            oct: 767,
            nov: 798,
            dec: 787,
            total: 9158,
          },
          {
            no: "3",
            department: "Shalya",
            jan: 869,
            feb: 867,
            mar: 857,
            apr: 880,
            may: 935,
            jun: 850,
            jul: 849,
            aug: 842,
            sep: 805,
            oct: 766,
            nov: 802,
            dec: 802,
            total: 10124,
          },
          {
            no: "4",
            department: "Shalakya Netra",
            jan: 678,
            feb: 657,
            mar: 627,
            apr: 676,
            may: 703,
            jun: 665,
            jul: 725,
            aug: 729,
            sep: 698,
            oct: 669,
            nov: 693,
            dec: 692,
            total: 8212,
          },
          {
            no: "5",
            department: "Shalakya Karna, Nasa and Mukha",
            jan: 663,
            feb: 666,
            mar: 623,
            apr: 667,
            may: 700,
            jun: 667,
            jul: 741,
            aug: 728,
            sep: 698,
            oct: 669,
            nov: 696,
            dec: 698,
            total: 8216,
          },
          {
            no: "6",
            department: "Prasuti & Stri Roga",
            jan: 919,
            feb: 896,
            mar: 851,
            apr: 886,
            may: 947,
            jun: 847,
            jul: 872,
            aug: 859,
            sep: 817,
            oct: 785,
            nov: 802,
            dec: 804,
            total: 10285,
          },
          {
            no: "7",
            department: "Kaumarbhritiya/Bal Roga",
            jan: 708,
            feb: 723,
            mar: 686,
            apr: 717,
            may: 706,
            jun: 698,
            jul: 797,
            aug: 799,
            sep: 772,
            oct: 740,
            nov: 767,
            dec: 767,
            total: 8880,
          },
          {
            no: "8",
            department: "Swastha Vritta & Yoga",
            jan: 231,
            feb: 235,
            mar: 221,
            apr: 242,
            may: 281,
            jun: 208,
            jul: 263,
            aug: 277,
            sep: 269,
            oct: 259,
            nov: 274,
            dec: 282,
            total: 3042,
          },
          {
            no: "9",
            department: "Agadyatantra (Casualty)",
            jan: 491,
            feb: 395,
            mar: 558,
            apr: 483,
            may: 432,
            jun: 458,
            jul: 426,
            aug: 463,
            sep: 418,
            oct: 503,
            nov: 411,
            dec: 446,
            total: 5456,
          },
          {
            no: "10",
            department: "Agad Vish Chikitsa",
            jan: 0,
            feb: 0,
            mar: 0,
            apr: 0,
            may: 0,
            jun: 137,
            jul: 278,
            aug: 293,
            sep: 265,
            oct: 255,
            nov: 280,
            dec: 288,
            total: 1796,
          },
          {
            no: "",
            department: "Month Total",
            jan: 6526,
            feb: 6447,
            mar: 6241,
            apr: 6462,
            may: 6663,
            jun: 6271,
            jul: 6827,
            aug: 6839,
            sep: 6555,
            oct: 6364,
            nov: 6523,
            dec: 6571,
            total: 78289,
          },
        ]}
      />
      <Table
        title={"IPD Data"}
        columns={[
          { label: "S.No", key: "no" },
          { label: "Name of the Departments", key: "department" },
          { label: "Jan", key: "jan" },
          { label: "Feb", key: "feb" },
          { label: "Mar", key: "mar" },
          { label: "Apr", key: "apr" },
          { label: "May", key: "may" },
          { label: "Jun", key: "jun" },
          { label: "Jul", key: "jul" },
          { label: "Aug", key: "aug" },
          { label: "Sep", key: "sep" },
          { label: "Oct", key: "oct" },
          { label: "Nov", key: "nov" },
          { label: "Dec", key: "dec" },
          { label: "Dept. Total", key: "total" },
        ]}
        data={[
          {
            no: "1",
            department: "Kayachikitsa",
            jan: 75,
            feb: 79,
            mar: 74,
            apr: 85,
            may: 77,
            jun: 71,
            jul: 75,
            aug: 67,
            sep: 69,
            oct: 65,
            nov: 68,
            dec: 65,
            total: 870,
          },
          {
            no: "2",
            department: "Panchakarma",
            jan: 14,
            feb: 10,
            mar: 11,
            apr: 16,
            may: 18,
            jun: 13,
            jul: 17,
            aug: 18,
            sep: 20,
            oct: 14,
            nov: 13,
            dec: 13,
            total: 177,
          },
          {
            no: "3",
            department: "Shalya",
            jan: 71,
            feb: 72,
            mar: 70,
            apr: 80,
            may: 76,
            jun: 74,
            jul: 74,
            aug: 69,
            sep: 64,
            oct: 67,
            nov: 69,
            dec: 67,
            total: 853,
          },
          {
            no: "4",
            department: "Shalakya",
            jan: 25,
            feb: 20,
            mar: 21,
            apr: 23,
            may: 25,
            jun: 23,
            jul: 25,
            aug: 29,
            sep: 26,
            oct: 24,
            nov: 23,
            dec: 26,
            total: 290,
          },
          {
            no: "5",
            department: "Prasuti & Stri Roga",
            jan: 88,
            feb: 85,
            mar: 79,
            apr: 87,
            may: 79,
            jun: 77,
            jul: 74,
            aug: 87,
            sep: 73,
            oct: 70,
            nov: 68,
            dec: 69,
            total: 936,
          },
          {
            no: "6",
            department: "Kaumarbhritiya (Balrog)",
            jan: 25,
            feb: 25,
            mar: 23,
            apr: 22,
            may: 28,
            jun: 25,
            jul: 26,
            aug: 28,
            sep: 28,
            oct: 24,
            nov: 24,
            dec: 25,
            total: 303,
          },
          {
            no: "7",
            department: "Agad Vish Chikitsa",
            jan: 0,
            feb: 0,
            mar: 0,
            apr: 0,
            may: 0,
            jun: 7,
            jul: 14,
            aug: 13,
            sep: 13,
            oct: 13,
            nov: 12,
            dec: 14,
            total: 86,
          },
          {
            no: "",
            department: "Month Total",
            jan: 298,
            feb: 291,
            mar: 278,
            apr: 313,
            may: 303,
            jun: 290,
            jul: 305,
            aug: 311,
            sep: 293,
            oct: 277,
            nov: 277,
            dec: 279,
            total: 3515,
          },
          {
            no: "",
            department: "Grand Total",
            jan: "",
            feb: "",
            mar: "",
            apr: "",
            may: "",
            jun: "",
            jul: "",
            aug: "",
            sep: "",
            oct: "",
            nov: "",
            dec: "",
            total: 3515,
          },
        ]}
      />
      <Table
        title={"Bed Occupied"}
        columns={[
          { label: "S.No", key: "no" },
          { label: "Name of the Departments", key: "department" },
          { label: "Jan", key: "jan" },
          { label: "Feb", key: "feb" },
          { label: "Mar", key: "mar" },
          { label: "Apr", key: "apr" },
          { label: "May", key: "may" },
          { label: "Jun", key: "jun" },
          { label: "Jul", key: "jul" },
          { label: "Aug", key: "aug" },
          { label: "Sep", key: "sep" },
          { label: "Oct", key: "oct" },
          { label: "Nov", key: "nov" },
          { label: "Dec", key: "dec" },
          { label: "Dept. Total", key: "total" },
        ]}
        data={[
          {
            no: "1",
            department: "Kayachikitsa",
            jan: 846,
            feb: 849,
            mar: 721,
            apr: 719,
            may: 778,
            jun: 705,
            jul: 678,
            aug: 726,
            sep: 703,
            oct: 733,
            nov: 576,
            dec: 721,
            total: 8755,
          },
          {
            no: "2",
            department: "Panchakarma",
            jan: 391,
            feb: 290,
            mar: 317,
            apr: 318,
            may: 389,
            jun: 412,
            jul: 432,
            aug: 453,
            sep: 390,
            oct: 435,
            nov: 422,
            dec: 435,
            total: 4684,
          },
          {
            no: "3",
            department: "Shalya",
            jan: 401,
            feb: 520,
            mar: 516,
            apr: 672,
            may: 694,
            jun: 704,
            jul: 728,
            aug: 730,
            sep: 708,
            oct: 729,
            nov: 597,
            dec: 717,
            total: 7716,
          },
          {
            no: "4",
            department: "Shalakya",
            jan: 145,
            feb: 136,
            mar: 149,
            apr: 132,
            may: 151,
            jun: 169,
            jul: 185,
            aug: 181,
            sep: 169,
            oct: 178,
            nov: 174,
            dec: 170,
            total: 1939,
          },
          {
            no: "5",
            department: "Prasuti & Stri Roga",
            jan: 660,
            feb: 650,
            mar: 620,
            apr: 629,
            may: 596,
            jun: 564,
            jul: 603,
            aug: 667,
            sep: 702,
            oct: 732,
            nov: 697,
            dec: 723,
            total: 7843,
          },
          {
            no: "6",
            department: "Kaumarbhritiya (Balrog)",
            jan: 178,
            feb: 180,
            mar: 176,
            apr: 143,
            may: 168,
            jun: 160,
            jul: 185,
            aug: 179,
            sep: 159,
            oct: 179,
            nov: 167,
            dec: 179,
            total: 2053,
          },
          {
            no: "7",
            department: "Agad Vish Chikitsa",
            jan: 0,
            feb: 0,
            mar: 0,
            apr: 0,
            may: 0,
            jun: 27,
            jul: 62,
            aug: 62,
            sep: 60,
            oct: 62,
            nov: 59,
            dec: 63,
            total: 395,
          },
          {
            no: "",
            department: "Month Total",
            jan: 2621,
            feb: 2625,
            mar: 2499,
            apr: 2613,
            may: 2776,
            jun: 2741,
            jul: 2873,
            aug: 2998,
            sep: 2891,
            oct: 3048,
            nov: 2692,
            dec: 3008,
            total: 33385,
          },
          {
            no: "",
            department: "Grand Total",
            jan: "",
            feb: "",
            mar: "",
            apr: "",
            may: "",
            jun: "",
            jul: "",
            aug: "",
            sep: "",
            oct: "",
            nov: "",
            dec: "",
            total: 33385,
          },
        ]}
      />
      <Table
        title={"Bed Existed"}
        columns={[
          { label: "S.No", key: "no" },
          { label: "Name of the Departments", key: "nameofdepartments" },
          { label: "No. of Existing Beds for UG", key: "existingbeds" },
          {
            label:
              "Additional Bed For existing PG/Clinical Dept): bed ratio 1:4",
            key: "additionalbeds",
          },
          { label: "Total no of available beds", key: "totalbeds" },
        ]}
        data={[
          {
            no: "1",
            nameofdepartments: "Kayachikitsa",
            existingbeds: "20",
            additionalbeds: "25",
            totalbeds: 45,
          },
          {
            no: "2",
            nameofdepartments: "Shalya",
            existingbeds: "20",
            additionalbeds: "25",
            totalbeds: 45,
          },
          {
            no: "3",
            nameofdepartments: "Shalakya",
            existingbeds: "10",
            additionalbeds: "0",
            totalbeds: 10,
          },
          {
            no: "4",
            nameofdepartments: "Prasuti & Stri Roga",
            existingbeds: "10",
            additionalbeds: "25",
            totalbeds: 35,
          },
          {
            no: "5",
            nameofdepartments: "Kaumarbhritya (Balrog)",
            existingbeds: "10",
            additionalbeds: "0",
            totalbeds: 10,
          },
          {
            no: "6",
            nameofdepartments: "Panchakarma",
            existingbeds: "25",
            additionalbeds: "0",
            totalbeds: 25,
          },
          {
            no: "7",
            nameofdepartments: "Agad Vish Chikitsa",
            existingbeds: "5",
            additionalbeds: "0",
            totalbeds: 5,
          },
        ]}
      />
    </>
  );
};

export default HospitalOPD_IPD_Data;
